### ISSUE TITLE
Delay on closing of test app

### ISSUE THREAD

**Issue by Alexey-T** [jdelauney/BZScene#6]
https://github.com/Alexey-T/FreePascal-tests/tree/master/Libs

On clicking X icon in test, i wait 5sec until program closes. 
This is not the case with BGRABitmap test.

linux x64 gtk2.

**Comment by jdelauney** [comment]
Hi,
 yes it is normal. It's to allow let time to the internal logger (thread) for shut down. I must refine {$ifdef DEBUG} preprocessor command. The lib is still in dev mode so i let the logger ON for the moment
