### ISSUE TITLE
Too big exe footprint

### ISSUE THREAD

**Issue by Alexey-T** [jdelauney/BZScene#7]
2 demos https://github.com/Alexey-T/FreePascal-tests/tree/master/Libs
Linux x64 gtk2

- bgrabitmap: binary size 7.3m
- bzscene: binary size 8.4m
Can it be smaller?

**Comment by jdelauney** [comment]
I can't open any of your project file. (i don't using the trunk) so i can't see tou project's options and see wich package you have  declared in dependancies.

for information, you only need to add "BZScene_Image_rt". BZScene_rt is already register into.
Same with BZScene_Engine_rt, where BZScene_Image_rt and BZScene_rt are automatically registered.

So, I recreate quickly your simple test

Under Windows in ( Release mode) 

![2020-09-09_200217](https://user-images.githubusercontent.com/29355534/92636836-4d2eec80-f2d8-11ea-8f1c-96df51d40efe.jpeg)
![2020-09-09_200301](https://user-images.githubusercontent.com/29355534/92636846-54ee9100-f2d8-11ea-92ad-de103753b4da.jpeg)

  - BGRABitmapTest = 3886 ko
  - BZSceneTest        = 3185 ko

I'll check under Linux and Mac soon as possible

**Comment by Alexey-T** [comment]
Re-saved LPI projects for old Laz versions. pls try.

**Comment by jdelauney** [comment]
It's not working, project is empty
![2020-09-09_202614](https://user-images.githubusercontent.com/29355534/92638644-e0692180-f2da-11ea-8314-b15da8a820ee.jpeg)
And if i add unit1, lfm +lpr manually Lazarus crash. 
![2020-09-09_203014](https://user-images.githubusercontent.com/29355534/92638882-4c4b8a00-f2db-11ea-9f23-cc0466cebc66.jpeg)

**Comment by Alexey-T** [comment]
Seems you didn't do "git pull" property, LPI now has old format and must be ok
```
<?xml version="1.0" encoding="UTF-8"?>
<CONFIG>
  <ProjectOptions>
    <Version Value="12"/>
    <General>
      <Flags>
        <CompatibilityMode Value="True"/>
      </Flags>
      <SessionStorage Value="InProjectDir"/>
      <Title Value="project1"/>
      <Scaled Value="True"/>
      <ResourceType Value="res"/>
      <UseXPManifest Value="True"/>
      <XPManifest>
        <DpiAware Value="True"/>
      </XPManifest>
    </General>
    <BuildModes Count="1">
      <Item1 Name="Default" Default="True"/>
    </BuildModes>
    <PublishOptions>
      <Version Value="2"/>
      <UseFileFilters Value="True"/>
    </PublishOptions>
    <RunParams>
      <FormatVersion Value="2"/>
    </RunParams>
    <RequiredPackages Count="2">
      <Item1>
        <PackageName Value="bzscene_engine_rt"/>
      </Item1>
      <Item2>
        <PackageName Value="LCL"/>
      </Item2>
    </RequiredPackages>
    <Units Count="2">
      <Unit0>
        <Filename Value="project1.lpr"/>
        <IsPartOfProject Value="True"/>
      </Unit0>
      <Unit1>
        <Filename Value="unit1.pas"/>
        <IsPartOfProject Value="True"/>
        <ComponentName Value="Form1"/>
        <HasResources Value="True"/>
        <ResourceBaseClass Value="Form"/>
        <UnitName Value="Unit1"/>
      </Unit1>
    </Units>
  </ProjectOptions>
  <CompilerOptions>
    <Version Value="11"/>
    <Target>
      <Filename Value="project1"/>
    </Target>
    <SearchPaths>
      <IncludeFiles Value="$(ProjOutDir)"/>
      <UnitOutputDirectory Value="lib/$(TargetCPU)-$(TargetOS)"/>
    </SearchPaths>
    <Linking>
      <Debugging>
        <GenerateDebugInfo Value="False"/>
        <UseExternalDbgSyms Value="True"/>
      </Debugging>
      <Options>
        <Win32>
          <GraphicApplication Value="True"/>
        </Win32>
      </Options>
    </Linking>
  </CompilerOptions>
  <Debugging>
    <Exceptions Count="3">
      <Item1>
        <Name Value="EAbort"/>
      </Item1>
      <Item2>
        <Name Value="ECodetoolError"/>
      </Item2>
      <Item3>
        <Name Value="EFOpenError"/>
      </Item3>
    </Exceptions>
  </Debugging>
</CONFIG>
```

**Comment by jdelauney** [comment]
Ok it work now

I saw you have include BZScene_engine_rt , so it's right.

i compiled both test. Results are sightly differents
BGABitmap = 3732 ko
BZScene = 3051 ko

I'll test under Linux tomorrow

**Comment by jdelauney** [comment]
Just a little tips, instead of

```
  b:= TBZBitmap.Create(300, 200);
  b.Clear(c0);
```
you can do, directly

```
  b:= TBZBitmap.Create(300, 200, c0);
```

**Comment by Alexey-T** [comment]
Thanks

**Comment by jdelauney** [comment]
I've checked under my Linux distro (Manjaro) and always with Lazarus 2.0.10 and FPC 3.2 64bit and with gtk2

Your generated file are more twice bigger than mine ! ouch !!! Why ????

> yours :
> bgrabitmap: binary size 7.3m
> bzscene: binary size 8.4m

Mine : 
- bgrabitmap: binary size : 4002 ko (3.8 Mo)
- bzscene: binary size : 3346 ko (3.2 Mo)

BZScene's tests are smaller than BGRABitmap under Windows and Linux. 
So i think, the problem must come from your Lazarus & FPC version
